default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: g2-rails-practice-dependent-destroy-development

test:
  <<: *default
  database: g2-rails-practice-dependent-destroy-test
