# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67f8f70772958925b9b7b6b086121b79447463a157002da4ab12e91358530a828025d9bac74e54c6ad283015be3d9497c6445d8e40b674c144032d39483820cd

test:
  secret_key_base: 6e600c659eff8f3de40206024d23c8fed971e3655f43756fd3d410d0725b7b4a96363c3cf6e95f6a9318d1dba0031db1ee286fcd597a81647e5d15e1760bf7a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
